[package]
name = "rgl"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "rgl"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.22", features = ["cargo"] }
dialoguer = "0.11.0"
dunce = "1.0.4"
indexmap = { version = "2.0.0", features = ["serde"] }
md5 = "0.7.0"
notify = "6.0.1"
notify-debouncer-mini = "0.3.0"
paris = { version = "1.5.15", features = ["macros"] }
rayon = "1.8.0"
reqwest = { version = "0.11.22", features = ["blocking"] }
semver = "1.0.18"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
tempfile = "3.8.1"
uuid = { version = "1.4.1", features = ["v4"] }
which = "4.4.2"
zip = "0.6.6"
