[[bin]]
name = "rgl"

[package]
name = "rgl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.22" }
log = "0.4.20"
notify = "6.0.1"
notify-debouncer-mini = "0.3.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
simplelog = { version = "0.12.1", features = ["paris"] }
